name: Deploy to GCP VPS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/class-scheduler:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Stop and remove existing containers
          docker-compose -f /opt/class-scheduler/docker-compose.yml down || true
          
          # Pull latest images
          docker pull ${{ secrets.DOCKER_USERNAME }}/class-scheduler:latest
          
          # Update the deployment
          cd /opt/class-scheduler
          git pull origin main || git pull origin master
          
          # Start services
          docker-compose up -d
          
          # Clean up unused images
          docker image prune -f