name: Deploy to GCP VPS

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Create app directory if it doesn't exist
          mkdir -p /home/kksimons/class-scheduler
          cd /home/kksimons/class-scheduler
          
          # Clone or update repository
          if [ -d ".git" ]; then
            git pull origin main || git pull origin master
          else
            git clone https://github.com/kksimons/class-scheduler.git .
          fi
          
          # Install Python dependencies with --break-system-packages
          python3 -m pip install --user --break-system-packages -r app/requirements.txt
          
          # Restart the systemd service (passwordless sudo required)
          sudo systemctl restart class-scheduler.service
          
          # Wait a moment and check if it's running
          sleep 3
          if sudo systemctl is-active --quiet class-scheduler.service; then
            echo "FastAPI app started successfully"
            sudo systemctl status class-scheduler.service --no-pager
            echo ""
            echo "Memory status after deployment:"
            free -h
            echo ""
            echo "Swap status:"
            sudo swapon --show || echo "No swap configured"
          else
            echo "Failed to start FastAPI app"
            sudo journalctl -u class-scheduler.service --no-pager -n 10
            echo ""
            echo "Memory status:"
            free -h
            exit 1
          fi